name = "backend"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19HWUhnVkxmQjNmbTg4b0poZGhyOEYiLCJhcGlfa2V5IjoiMDFLVjNGOEJER1BROERHQkhIQVNHR002V0IiLCJ0ZW5hbnRfaWQiOiI1ODE0OTk4ZmYwODgwNDczNmEyMzZhOWY1ZWU4NTZkMTc4OGYxNWMyM2UyNzZiZGE3YTBmMzkwM2MxOTEyOTAyIiwiaW50ZXJuYWxfc2VjcmV0IjoiN2M1ZWVlOGUtNjQ2YS00NDg0LThkZmItZDBjNjA1MGY0MDczIn0.dT0PceyRLtYUwYmaXDFm9C07yYj2HJQ2RM7SqmhQs9o"
JWT_SECRET="mysecretkey"
